###
GET  http://localhost:8000/user

###
GET  http://localhost:8000/user/62dfcc7edddc51723ceb90df

###
POST http://localhost:8000/user/register
Content-Type: application/json

{
    "name":"Pedro Fernandez",
    "email":"pedrofer@gmail.com",
    "password":"abcabc"
}

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email":"pedro@gmail.com",
    "password":"abcabc"
}

###
DELETE http://localhost:8000/user/delete/62dfd7b2519064a66b642c13

###
DELETE http://localhost:8000/user/delete/users

###
PUT http://localhost:8000/user/update/62dfddcdc6c5924f08f4171c
Content-Type: application/json

{
    "email":"pedro@gmail.com"
}