###
GET  http://localhost:8000/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTNkNjAwZTUxYWJhYmIxMzAxZjEwYyIsImVtYWlsIjoiam92aXZhc3BvQGdtYWlsLmNvbSIsImlhdCI6MTY1OTUxMzEwNCwiZXhwIjoxNjU5NTk5NTA0fQ.VrLpNKTppfw6cOG1aly1mOpdTZS2CKcD5cQ_j0mfQhQ


###
GET  http://localhost:8000/user/62ea32dabb7e4ab335732a35
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWEzMmRhYmI3ZTRhYjMzNTczMmEzNSIsImVtYWlsIjoiam9yZ2V2aXZhc0Bpbm5vZ2VzdGlvbmEuZXMiLCJpYXQiOjE2NTk1MTU3NzcsImV4cCI6MTY1OTYwMjE3N30.FTu2DLGvybAxzvX9MF5ALd-sotRLWYZCNs43v1Bvre4

###
POST http://localhost:8000/user/register
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTNkNjAwZTUxYWJhYmIxMzAxZjEwYyIsImVtYWlsIjoiam92aXZhc3BvQGdtYWlsLmNvbSIsImlhdCI6MTY1OTUxMzEwNCwiZXhwIjoxNjU5NTk5NTA0fQ.VrLpNKTppfw6cOG1aly1mOpdTZS2CKcD5cQ_j0mfQhQ

{
    "name":"jorge usuario",
    "email":"jorgevivas@innogestiona.es",
    "password":"abcabc"
}

###
GET  http://localhost:8000/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWEyZjM2NmQzZGRlYmUyNTU2ZjA2ZSIsImVtYWlsIjoiam9yZ2V2aXZhc0Bpbm5vZ2VzdGlvbmEuZXMiLCJpYXQiOjE2NTk1MTQ2NzgsImV4cCI6MTY1OTYwMTA3OH0.qq0dCckCHf3e8FJ81yE0rJceeaeSmcHGK6slsOTJ41g
###
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email":"jorgevivas@innogestiona.es",
    "password":"abcabc"
}

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email":"david@gmail.com",
    "password":"abcabc"
}


###
DELETE http://localhost:8000/user/delete/62ea3267bb7e4ab335732a28
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTNkNjAwZTUxYWJhYmIxMzAxZjEwYyIsImVtYWlsIjoiam92aXZhc3BvQGdtYWlsLmNvbSIsImlhdCI6MTY1OTUxMzEwNCwiZXhwIjoxNjU5NTk5NTA0fQ.VrLpNKTppfw6cOG1aly1mOpdTZS2CKcD5cQ_j0mfQhQ

###
DELETE http://localhost:8000/user/delete/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGZjYzdlZGRkYzUxNzIzY2ViOTBkZiIsImVtYWlsIjoiam92aXZhc3BvQGdtYWlsLmNvbSIsImlhdCI6MTY1OTA5NjAzMCwiZXhwIjoxNjU5MTgyNDMwfQ.BnKs6LvM9CzaPkKZP6bgvN1Vp94r04GvC8gmwB9CvHM


###
PUT http://localhost:8000/user/update/62e3cce7fe3c552ee8f18742
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTNjY2U3ZmUzYzU1MmVlOGYxODc0MiIsImVtYWlsIjoiZGF2aWRAZ21haWwuY29tIiwiaWF0IjoxNjU5MDk2NDc3LCJleHAiOjE2NTkxODI4Nzd9.plDc2_uljwNfZ97itOk9KawsYSeXEZXL2f1waEjKK9c

{
    "email":"davidSerrano@gmail.com"
}